spring:
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
          
server:
  port: 8888

management:
  security:
    enabled: false
    
logging:
  level:
    root: INFO
    org.springframework.boot.context.config: TRACE